# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/student/Downloads/Linux_Unreal_Engine_5.6.1

TARGETS = \
	TempoCameraTest-Android-DebugGame  \
	TempoCameraTest-Android-Development  \
	TempoCameraTest-Android-Shipping  \
	TempoCameraTest-Linux-DebugGame  \
	TempoCameraTest-Linux-Development  \
	TempoCameraTest-Linux-Shipping  \
	TempoCameraTest-LinuxArm64-DebugGame  \
	TempoCameraTest-LinuxArm64-Development  \
	TempoCameraTest-LinuxArm64-Shipping  \
	TempoCameraTest \
	TempoCameraTestEditor-Linux-DebugGame  \
	TempoCameraTestEditor-Linux-Development  \
	TempoCameraTestEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TempoCameraTestEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TempoCameraTestEditor-Linux-Debug


TempoCameraTest-Android-DebugGame:
	 $(BUILD) TempoCameraTest Android DebugGame  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest-Android-Development:
	 $(BUILD) TempoCameraTest Android Development  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest-Android-Shipping:
	 $(BUILD) TempoCameraTest Android Shipping  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest-Linux-DebugGame:
	 $(BUILD) TempoCameraTest Linux DebugGame  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest-Linux-Development:
	 $(BUILD) TempoCameraTest Linux Development  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest-Linux-Shipping:
	 $(BUILD) TempoCameraTest Linux Shipping  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest-LinuxArm64-DebugGame:
	 $(BUILD) TempoCameraTest LinuxArm64 DebugGame  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest-LinuxArm64-Development:
	 $(BUILD) TempoCameraTest LinuxArm64 Development  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest-LinuxArm64-Shipping:
	 $(BUILD) TempoCameraTest LinuxArm64 Shipping  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTest: TempoCameraTest-Linux-Development

TempoCameraTestEditor-Linux-DebugGame:
	 $(BUILD) TempoCameraTestEditor Linux DebugGame  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTestEditor-Linux-Development:
	 $(BUILD) TempoCameraTestEditor Linux Development  -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" $(ARGS)

TempoCameraTestEditor: TempoCameraTestEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/student/Desktop/Kandidatarbete_2026/UE5/TempoCameraTest/TempoCameraTest.uproject" -Game 

.PHONY: $(TARGETS)
